uoft_python_cli(
    description = "CLI and API to manage a Bluecat instance",
    author = "Alex Tremblay",
    author_email = "alex.tremblay@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/bluecat/cli",
    pex_kwargs = dict(
        dependencies = [
            # [[[cog tasks._coghelpers.compute_pants_dist_deps('uoft/bluecat/cli')]]]
            "src/uoft/bluecat:dist",
            "src/uoft/core:dist",
            # [[[end]]]
        ]
    ),
)
