uoft_python_cli(
    description = "API Wrapper and (hopefully soon) CLI interface for the LibreNMS REST API",
    author = "Alex Tremblay",
    author_email = "alex.tremblay@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/librenms/cli",
)
