[GLOBAL]
pants_version = "2.11.0"
backend_packages = [
  "pants.backend.docker",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.pylint",
  "pants.backend.python.lint.isort",
  "pants.backend.experimental.python.packaging.pyoxidizer",
]

[python]
interpreter_constraints = [">=3.10"]
tailor_ignore_solitary_init_files = false

# Enable the "resolves" mechanism, which turns on lockfiles for user code. See
# https://www.pantsbuild.org/docs/python-third-party-dependencies. This also adds the
# `generate-lockfiles` goal for Pants to generate the lockfile for you, although in some
# situations you may need to manually generate it, as explained in the docs.
enable_resolves = true
resolves = { python-default = "lockfile.txt"}

# Enable using the PEX lockfile format, which provides support for custom indexes, and
# improves performance for large repositories.
lockfile_generator = "pex"

[python-infer]
inits = true


[anonymous-telemetry]
enabled = true
repo_id = "c2cee4a4-ed53-402e-817d-999a829dbbfa"