[project]
name = "uoft"
version = "0.1.0"
readme = "README.md"
requires-python = ">= 3.10"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "black>=22.3.0",
    "build",
    "cogapp>=3.3",
    "copier>=7",
    "invoke>=1.7",
    "ipython>=8",
    "mypy>=0.971",
    "ptpython>=3.0",
    "pylint",
    "pytest>=7.0",
    "pytest-cov",
    "pytest-mock>=3.6",
    "pytest-recording",
    "pytest-relaxed",
    "ruff>=0.0.149",
    "setuptools_scm>=7",
    "tomlkit>=0.11",
    "typer-cli",
    # python-ldap, required by django-auth-ldap, required by uoft_nautobot
    # ONLY ships as a source distribution, does not provide wheels.
    # it is notoriously difficult and finicky to build on some platforms, 
    # so we provide pre-built wheels for the most common platforms.
    "python-ldap @ https://github.com/uoft-networking/python-ldap/releases/download/latest/python_ldap-3.4.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ; sys_platform == 'linux' and python_version == '3.10' and platform_machine == 'x86_64'",
    "python-ldap @ https://github.com/uoft-networking/python-ldap/releases/download/latest/python_ldap-3.4.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ; sys_platform == 'linux' and python_version == '3.10' and platform_machine == 'arm64'",
    "python-ldap @ https://github.com/uoft-networking/python-ldap/releases/download/latest/python_ldap-3.4.3-cp310-cp310-macosx_10_9_universal2.whl ; sys_platform == 'darwin' and python_version == '3.10'",
]

[tool.rye.workspace]
members = ["projects/*"]

[[tool.rye.sources]]
name = "python-ldap-builds"
url = "https://github.com/uoft-networking/python-ldap/releases/tag/latest"
type = "find-links"

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests", "projects/**/tests"]
norecursedirs = [
    "**/fixtures",
    "dist",
    "build",
    "docs",
    "hazmat",
    ".venv",
    ".tox",
    ".nox",
    ".git",
    ".hg",
    ".mypy_cache",
    ".ruff_cache",
    ".pants.d",
]
python_files = ["*"] # enable support for assertion-rewriting in "pytest-relaxed" test suites

[tool.ruff]
line-length = 120

typing-modules = ["uoft_core.types"]

# Enable Flake's "E", "W", and "F" codes by default.
select = ["E", "W", "F", "RUF"]
ignore = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"
