[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.poe.tasks]
publish.script = "tools:call('publish')"
bump_version.script = "tools:call('bump_version')"
build.script = "tools:call('build')"
cov.cmd = "pytest --cov-report xml:cov.xml --cov-report term-missing --cov"
check.shell = """\
  black .
  mypy .
  prospector .
  pytest .
  """
nautobot.cmd = "poe --root projects/nautobot"

[tool.monas]
packages = ["projects/"]
version = "1.0.0"
python-version = "3.10"
