uoft_python_cli(
    description = "Occupancy tracking",
    author = "Kyle Fozo",
    author_email = "kyle.fozo@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/occupancy/cli",
)
