# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enrollment.proto
# Protobuf Python Version: 6.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'enrollment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65nrollment.proto\x12\x05\x61\x64min\x1a google/protobuf/field_mask.proto\x1a\x1egoogle/protobuf/duration.proto\"\xa6\x01\n\x0f\x45nrollmentToken\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06groups\x18\x02 \x03(\t\x12\x17\n\x0freenrollDevices\x18\x03 \x03(\t\x12+\n\x08validFor\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12.\n\nfield_mask\x18\x64 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"L\n\x19\x41\x64\x64\x45nrollmentTokenRequest\x12/\n\x0f\x65nrollmentToken\x18\x01 \x01(\x0b\x32\x16.admin.EnrollmentToken\"M\n\x1a\x41\x64\x64\x45nrollmentTokenResponse\x12/\n\x0f\x65nrollmentToken\x18\x01 \x01(\x0b\x32\x16.admin.EnrollmentToken\"W\n\x06\x44\x65vice\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06groups\x18\x02 \x03(\t\x12*\n\x0b\x64\x65vice_type\x18\x03 \x01(\x0e\x32\x11.admin.DeviceTypeB\x02\x18\x01\"1\n\x10\x41\x64\x64\x44\x65viceRequest\x12\x1d\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\r.admin.Device\"2\n\x11\x41\x64\x64\x44\x65viceResponse\x12\x1d\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\r.admin.Device*V\n\nDeviceType\x12\x1b\n\x17\x44\x45VICE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x44\x45VICE_TYPE_WIRED\x10\x01\x12\x14\n\x10\x44\x45VICE_TYPE_WIFI\x10\x02\x32\xa7\x01\n\nEnrollment\x12Y\n\x12\x41\x64\x64\x45nrollmentToken\x12 .admin.AddEnrollmentTokenRequest\x1a!.admin.AddEnrollmentTokenResponse\x12>\n\tAddDevice\x12\x17.admin.AddDeviceRequest\x1a\x18.admin.AddDeviceResponseB+Z)arista/aeris/service/admin/enrollment/genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enrollment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)arista/aeris/service/admin/enrollment/gen'
  _globals['_DEVICE'].fields_by_name['device_type']._loaded_options = None
  _globals['_DEVICE'].fields_by_name['device_type']._serialized_options = b'\030\001'
  _globals['_DEVICETYPE']._serialized_start=611
  _globals['_DEVICETYPE']._serialized_end=697
  _globals['_ENROLLMENTTOKEN']._serialized_start=94
  _globals['_ENROLLMENTTOKEN']._serialized_end=260
  _globals['_ADDENROLLMENTTOKENREQUEST']._serialized_start=262
  _globals['_ADDENROLLMENTTOKENREQUEST']._serialized_end=338
  _globals['_ADDENROLLMENTTOKENRESPONSE']._serialized_start=340
  _globals['_ADDENROLLMENTTOKENRESPONSE']._serialized_end=417
  _globals['_DEVICE']._serialized_start=419
  _globals['_DEVICE']._serialized_end=506
  _globals['_ADDDEVICEREQUEST']._serialized_start=508
  _globals['_ADDDEVICEREQUEST']._serialized_end=557
  _globals['_ADDDEVICERESPONSE']._serialized_start=559
  _globals['_ADDDEVICERESPONSE']._serialized_end=609
  _globals['_ENROLLMENT']._serialized_start=700
  _globals['_ENROLLMENT']._serialized_end=867
# @@protoc_insertion_point(module_scope)
