uoft_python_cli(
    description = "A collection of tools to interact with a phpIPAM instance.",
    author = "Alex Tremblay",
    author_email = "alex.tremblay@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/phpipam/cli",
)