uoft_python_cli(
    description = "Custom SSH wrapper which automatically handles authentication and provides a keyboard shortcut to insert the enable password on the switch",
    author = "Alex Tremblay",
    author_email = "alex.tremblay@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/ssh/cli",
)