uoft_python_cli(
    description = "CLI and API to work with Paloalto products (NSM, etc)",
    author = "Alex Tremblay",
    author_email = "alex.tremblay@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/paloalto/cli",
)
