name:
  type: str
  help: What is the name of your project?

description:
  type: str
  help: Give me a one-sentence description of your project

author_name:
  type: str
  help: What is your full name?

author_email:
  type: str
  help: what is your email address?