[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
# requires = ["poetry-core @ git+https://github.com/atremblay/poetry-core.git@fix-issue-5621"]
# build-backend = "poetry.core.masonry.api"

[tool.hatch.build]
packages = ["utsc"]

[project]
name = "utsc.switchconfig"
version = "2022.4.26.1"
description = "A tool to easily provision switches on the bench"
readme = "README.md"
authors = [
  { name = "Alex Tremblay", email = "alex.tremblay@utoronto.ca" }, 
  { name = "University of Toronto Governing Council", email = "governing.council@utoronto.ca" }
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "utsc.core",
  "Jinja2 >= 3.0.1",
  "pydantic >= 1.9.0",
  "arrow >= 1.1.1",
  "prompt-toolkit >= 3.0.19",
  "paramiko >= 2.7.2",
  "pexpect >= 4.8.0",
  "rich >= 10.7.0",
  "ipdb >= 0.13.9",
  "netaddr >= 0.8.0",
]

[project.scripts]
"utsc.switchconfig" = "utsc.switchconfig.__main__:cli"

# [tool.poetry]
# name = "utsc.switchconfig"
# version = "2022.4.26.1"
# description = "A tool to easily provision switches on the bench"
# authors = ["Alex Tremblay <alex.tremblay@utoronto.ca>", "University of Toronto Governing Council <governing.council@utoronto.ca>"]
# license = "MIT"
# packages = [
#   { include = "utsc/switchconfig", from = "../../src" }
# ]

# [tool.poetry.scripts]
# "utsc.switchconfig" = "utsc.switchconfig.__main__:cli"

# [tool.poetry.dependencies]
# python = ">=3.10,<4.0"
# "utsc.core" = "*"
# Jinja2 = ">=3.0.1"
# pydantic = ">=1.9.0"
# arrow = ">=1.1.1"
# prompt-toolkit = ">=3.0.19"
# paramiko = ">=2.7.2"
# pexpect = ">=4.8.0"
# rich = ">=10.7.0"
# ipdb = ">=0.13.9"
# netaddr = ">=0.8.0"

# [tool.poetry.dev-dependencies]
# "utsc.core" = {path = "../core", develop = true}