uoft_python_lib(
    sources_kwargs={
        "dependencies": [ 
            # deps not directly imported by our code, but used at runtime
            # by utsc-specific code
            '//:py-deps#glom',
            '//:py-deps#python-box',
        ],
    },
)

