[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
# requires = ["poetry-core @ git+https://github.com/atremblay/poetry-core.git@fix-issue-5621"]
# build-backend = "poetry.core.masonry.api"

[tool.hatch.build]
packages = ["utsc"]

[project]
name = "utsc.scripts"
version = "2022.05.26"
description = "a collection of scripts and one-off tools"
readme = "README.md"
authors = [
  { name = "Alex Tremblay", email = "alex.tremblay@utoronto.ca" }, 
  { name = "University of Toronto Governing Council", email = "governing.council@utoronto.ca" }
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "utsc.core",
  "pydantic >= 1.9.0",
  "prompt-toolkit >= 3.0.19",
  "rich >= 10.7.0",
  "pyquery >= 1.4.0",
  "ldap3"
]

[project.scripts]
"utsc.scripts" = "utsc.scripts.__main__:cli"

[tool.poe.tasks]
cov.cmd = "pytest --cov-report xml:cov.xml --cov-report term-missing --cov"
publish.cmd = "git push origin main --tags"
sudo-install.shell = """\
    rm -f dist/*
    poetry build
    sudo /usr/local/bin/pip3 install dist/*.whl
    """
check.shell = """\
    black .
    mypy .
    prospector .
    pytest .
    """


# [tool.poetry]
# name = "utsc.scripts"
# version = "2022.4.26"
# description = "a collection of scripts and one-off tools"
# authors = ["Alex Tremblay <alex.tremblay@utoronto.ca>", "University of Toronto Governing Council <governing.council@utoronto.ca>"]
# license = "MIT"
# packages = [
#   { include = "utsc/scripts", from = "../../src" }
# ]


# [tool.poetry.scripts]
# "utsc.scripts" = "utsc.scripts.__main__:cli"

# [tool.poetry.dependencies]
# python = ">=3.10,<4.0"
# "utsc.core" = "*"
# pydantic = ">=1.9.0"
# prompt-toolkit = ">=3.0.19"
# rich = ">=10.7.0"
# requests = ">=2.20.0"
# pyquery = ">=1.4.0"
# ldap3 = "*"


# [tool.poetry.dev-dependencies]
# "utsc.core" = {path = "../core", develop = true}