[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
# requires = ["poetry-core @ git+https://github.com/atremblay/poetry-core.git@fix-issue-5621"]
# build-backend = "poetry.core.masonry.api"

[tool.hatch.build]

[project]
name = "uoft_scripts"
version = "1.0.0"
description = "a collection of scripts and one-off tools"
readme = "README.md"
authors = [
  { name = "Alex Tremblay", email = "alex.tremblay@utoronto.ca" },
  { name = "University of Toronto Governing Council", email = "governing.council@utoronto.ca" },
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "uoft_core",
  "pydantic >= 1.9.0",
  "prompt-toolkit >= 3.0.19",
  "rich >= 10.7.0",
  "pyquery >= 1.4.0",
  "ldap3",
]

[project.scripts]
"uoft_scripts" = "uoft_scripts.__main__:cli"

[tool.poe.tasks]
cov.cmd = "pytest --cov-report xml:cov.xml --cov-report term-missing --cov"
publish.cmd = "git push origin main --tags"
sudo-install.shell = """\
    rm -f dist/*
    poetry build
    sudo /usr/local/bin/pip3 install dist/*.whl
    """
check.shell = """\
    black .
    mypy .
    prospector .
    pytest .
    """
