[project]
name = "uoft_scripts"
description = "a collection of scripts and one-off tools"
readme = "README.md"
authors = [
  { name = "Alex Tremblay", email = "alex.tremblay@utoronto.ca" },
  { name = "University of Toronto", email = "alex.tremblay@utoronto.ca" },
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "uoft_core",
  "uoft_bluecat",
  "uoft_ssh",
  "pynautobot >= 2.1.1",
  "jinja2",
  "deepdiff",
  "python-box",
  "glom",
  "pydantic >= 1.9.0",
  "prompt-toolkit >= 3.0.19",
  "rich >= 10.7.0",
  "pyquery >= 1.4.0",
  "ldap3",
]
dynamic = ["version"]

[project.scripts]
uoft-scripts = "uoft_scripts.cli:cli"

[build-system]
requires = ["hatchling >= 1.6.0", "setuptools_scm"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.metadata.hooks.custom]
path = "pyproject.py"

[tool.hatch.build]
only-packages = true
packages = ["uoft_scripts"]
exclude = ["**/tests"]
