# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: tasks/new_project_template
author_email: alex.tremblay@utoronto.ca
author_name: Alex Tremblay
description: API Wrapper and (hopefully soon) CLI interface for the LibreNMS REST
    API
name: librenms
