# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: tasks/new_project_template
author_email: kyle.fozo@utoronto.ca
author_name: Kyle-Fozo
description: UofT Grist - Utilization Reporting
name: grist
