[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
# requires = ["poetry-core @ git+https://github.com/atremblay/poetry-core.git@fix-issue-5621"]
# build-backend = "poetry.core.masonry.api"

[tool.hatch.build]
packages = ["uoft_nautobot"]


[project]
name = "uoft_nautobot"
version = "1.0.1.dev2"
description = "A collection of UofT-specific modifications and extensions to Nautobot."
readme = "README.md"
authors = [
  { name = "Alex Tremblay", email = "alex.tremblay@utoronto.ca" },
  { name = "University of Toronto Governing Council", email = "governing.council@utoronto.ca" },
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "nautobot_ssot >= 1.1.0",
  "nautobot_golden_config",
  "uoft_core",
  "nautobot >= 1.3",
  "django-auth-ldap",
  "debugpy",
  "django-debug-toolbar",
  "html-table-parser-python3 >=0.2.0",
  "django-environ",
  "napalm",
  "librenms_handler",
  "python-box",
]
