[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
# requires = ["poetry-core @ git+https://github.com/atremblay/poetry-core.git@fix-issue-5621"]
# build-backend = "poetry.core.masonry.api"

[tool.hatch.build]
packages = ["utsc_nautobot"]

[project]
name = "utsc_nautobot"
version = "2022.05.17"
description = "A collection of UTSC-specific modifications and extensions to Nautobot."
readme = "README.md"
authors = [
  { name = "Alex Tremblay", email = "alex.tremblay@utoronto.ca" }, 
  { name = "University of Toronto Governing Council", email = "governing.council@utoronto.ca" }
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "nautobot_ssot >= 1.1.0",
  "utsc.core",
  "nautobot >= 1.3",
  "django-auth-ldap",
  "debugpy",
  "django-debug-toolbar",
  "html-table-parser-python3 >=0.2.0",
  "django-environ"
]

[tool.poe.tasks]
start.cmd = "nautobot-server start --ini dev_data/uwsgi.ini"
systemd.cmd = "sudo systemctl $action nautobot-dev.service nautobot-dev-scheduler.service nautobot-dev-worker.service"
systemd.args = [{name = 'action', positional = true}]
systemd-edit.shell = "sudoedit /etc/systemd/system/nautobot-dev.service /etc/systemd/system/nautobot-dev-worker.service /etc/systemd/system/nautobot-dev-scheduler.service; sudo systemctl daemon-reload"
systemd-tail.cmd = "sudo journalctl -f -u nautobot-dev -u nautobot-dev-worker -u nautobot-dev-scheduler"
prod-systemd.cmd = "sudo systemctl $action nautobot.service nautobot-scheduler.service nautobot-worker.service"
prod-systemd.args = [{name = 'action', positional = true}]
prod-systemd-edit.shell = "sudoedit /etc/systemd/system/nautobot.service /etc/systemd/system/nautobot-worker.service /etc/systemd/system/nautobot-scheduler.service; sudo systemctl daemon-reload"
prod-systemd-tail.cmd = "sudo journalctl -f -u nautobot -u nautobot-worker -u nautobot-scheduler"
prod-shell.cmd = "sudo -u nautobot env -C /opt/nautobot bash --login"
prod-deploy-hotfix.shell = '''
rm -rf dist
hatchling build
gpipx runpip nautobot uninstall utsc_nautobot
gpipx inject nautobot dist/*.whl
'''
db-refresh.shell = '''
poe systemd stop
/opt/backups/db/actions sync_prod_to_dev
nautobot-server migrate
poe systemd start
'''

# [tool.poetry]
# name = "utsc_nautobot"
# version = "2022.5.16"
# description = "A collection of UTSC-specific modifications and extensions to Nautobot."
# authors = ["Alex Tremblay <alex.tremblay@utoronto.ca>", "University of Toronto Governing Council <governing.council@utoronto.ca>"]
# license = "MIT"
# packages = [
#   { include = "utsc_nautobot", from = "../../src" }
# ]

# [tool.poetry.dependencies]
# python = ">=3.10,<4.0"
# nautobot_ssot = ">=1.1.0"
# "utsc.core" = "*"
# nautobot = ">=1.3"
# django-auth-ldap = "*" 
# debugpy = "*"
# django-debug-toolbar = "*"
# html-table-parser-python3 = ">=0.2.0"
# django-environ = "*"


# [tool.poetry.dev-dependencies]
# "utsc.core" = {path = "../core", develop = true}
# django-environ = {git = "https://github.com/alextremblay/django-environ", rev = "main"}