uoft_python_cli(
    description = "Collection of tools to interact with SnipeIT, currently focused around Access Point provisioning, but will probably be expanded to support all asset types in general.",
    author = "Alex Tremblay",
    author_email = "alex.tremblay@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/snipeit/cli",
)