uoft_python_cli(
    description = "Collection of utilities for interacting with Aruba infrastructure",
    author = "Kyle Fozo",
    author_email = "kyle.fozo@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/aruba/cli",
)