# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: tasks/new_project_template
author_email: alex.tremblay@utoronto.ca
author_name: Alex Tremblay
description: A toolkit for working with SSH. Wrappers, Ansible convenience features,
    Nornir integration, etc
name: ssh
