import pytest


def test_module_imports():
    "Sanity check: is every module in the monorepo importable?"

    # to make nautobot modules importable:
    import sys

    sys.path.insert(0, "projects/nautobot/.dev_data")
    # import os
    # os.environ["NAUTOBOT_CONFIG"] = "projects/nautobot/.dev_data/nautobot_config.py"
    # os.environ["NAUTOBOT_ROOT"] = "projects/nautobot/.dev_data"
    # [[[cog tasks._coghelpers.all_importable_modules()]]]
    importable_modules = [
        "apps.port_activation",
        "uoft.snipeit.print",
        "uoft.snipeit.mkinventorylabel",
        "uoft.snipeit.version",
        "uoft.snipeit.location_lookup",
        "uoft.snipeit.create",
        "uoft.snipeit.serial_lookup",
        "uoft.snipeit.conf",
        "uoft.snipeit.__main__",
        "uoft.snipeit.batch",
        "uoft.snipeit.generate",
        "uoft.snipeit.checkout",
        "uoft.snipeit.api",
        "uoft.phpipam.version",
        "uoft.phpipam.serial_lookup",
        "uoft.phpipam.conf",
        "uoft.phpipam.__main__",
        "uoft.phpipam.ansible_lookup",
        "uoft.phpipam.api",
        "uoft.librenms.typing",
        "uoft.librenms.version",
        "uoft.librenms.conf",
        "uoft.librenms.__main__",
        "uoft.librenms.api",
        "uoft.aruba.version",
        "uoft.aruba.conf",
        "uoft.aruba.batch",
        "uoft.aruba.api",
        "uoft.aruba.cli.station_blocklist",
        "uoft.aruba.cli.list_aps",
        "uoft.aruba.cli.__main__",
        "uoft.aruba.cli.cpsec_allowlist",
        "uoft.occupancy.version",
        "uoft.occupancy.conf",
        "uoft.occupancy.__main__",
        "uoft.paloalto.version",
        "uoft.paloalto.conf",
        "uoft.paloalto.__main__",
        "uoft.paloalto.api",
        "uoft.bluecat.type_stubs",
        "uoft.bluecat.version",
        "uoft.bluecat.conf",
        "uoft.bluecat.__main__",
        "uoft.bluecat.api",
        "uoft.ssh.util",
        "uoft.ssh.version",
        "uoft.ssh.conf",
        "uoft.ssh.__main__",
        "uoft.ssh.pexpect_utils",
        "uoft.scripts.other",
        "uoft.scripts._sync",
        "uoft.scripts.version",
        "uoft.scripts._jinja",
        "uoft.scripts.nornir",
        "uoft.scripts.base",
        "uoft.scripts.cli.librenms",
        "uoft.scripts.cli.cli",
        "uoft.scripts.cli.arista",
        "uoft.scripts.cli.sib_turnup",
        "uoft.scripts.cli.__main__",
        "uoft.scripts.cli.ldap",
        "uoft.scripts.cli.nautobot",
        "uoft.scripts.sib_turnup",
        "uoft.scripts.sib_turnup.lib",
        "uoft.scripts.librenms",
        "uoft.scripts.librenms.lib",
        "uoft.scripts.nautobot",
        "uoft.scripts.nautobot.lib",
        "uoft.scripts.stg_ipam_dev",
        "uoft.scripts.stg_ipam_dev.lib",
        "uoft.scripts.ldap",
        "uoft.scripts.ldap.lib",
        "uoft.scripts.arista",
        "uoft.scripts.arista.lib",
        "uoft.switchconfig.cli",
        "uoft.switchconfig.util",
        "uoft.switchconfig.version",
        "uoft.switchconfig.conf",
        "uoft.switchconfig.generate",
        "uoft.switchconfig.types",
        "uoft.switchconfig.deploy",
        "uoft.switchconfig.example_template_dir",
        "uoft.core.logging",
        "uoft.core.typing",
        "uoft.core.other",
        "uoft.core",
        "uoft.core.jinja",
        "uoft.core.version",
        "uoft.core.console",
        "uoft.core.__main__",
        "uoft.core.nested_data",
        "uoft.core.prompt",
        "uoft.core.types",
        "uoft.core.api",
        "uoft.core.toml",
        "uoft.core.toml._re",
        "uoft.core.toml._parser",
        "uoft.core.toml._writer",
        "uoft.core.yaml.scalarbool",
        "uoft.core.yaml.scanner",
        "uoft.core.yaml.emitter",
        "uoft.core.yaml",
        "uoft.core.yaml.nodes",
        "uoft.core.yaml.events",
        "uoft.core.yaml.util",
        "uoft.core.yaml.scalarfloat",
        "uoft.core.yaml.scalarstring",
        "uoft.core.yaml.parser",
        "uoft.core.yaml.main",
        "uoft.core.yaml.composer",
        "uoft.core.yaml.compat",
        "uoft.core.yaml.anchor",
        "uoft.core.yaml.tokens",
        "uoft.core.yaml.resolver",
        "uoft.core.yaml.scalarint",
        "uoft.core.yaml.constructor",
        "uoft.core.yaml.representer",
        "uoft.core.yaml.comments",
        "uoft.core.yaml.serializer",
        "uoft.core.yaml.timestamp",
        "uoft.core.yaml.error",
        "uoft.core.yaml.io",
        "uoft_nautobot.scripts_prelude",
        "uoft_nautobot.datasources",
        "uoft_nautobot",
        "uoft_nautobot.jinja_filters",
        "uoft_nautobot.auth",
        "uoft_nautobot.version",
        "uoft_nautobot.urls",
        "uoft_nautobot.secrets",
        "uoft_nautobot.template_content",
        "uoft_nautobot.golden_config",
        "uoft_nautobot.excel",
        "uoft_nautobot.jobs",
        "uoft_nautobot.api",
        "uoft_nautobot.api.views",
        "uoft_nautobot.api.urls",
        "uoft_nautobot.management.commands.run_script",
    ]
    # [[[end]]]
