uoft_python_cli(
    description = "A tool to easily provision switches on the bench",
    author = "Alex Tremblay",
    author_email = "alex.tremblay@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/switchconfig/cli",
    pex_kwargs = dict(
        dependencies = [
            # [[[cog tasks._coghelpers.compute_pants_dist_deps('uoft/switchconfig/cli')]]]
            "src/uoft/core:dist",
            "src/uoft/switchconfig:dist",
            # [[[end]]]
        ]
    ),
)