uoft_python_cli(
    description = "A tool to easily provision switches on the bench",
    author = "Alex Tremblay",
    author_email = "alex.tremblay@utoronto.ca",
    license = "MIT",
    url = "https://github.com/uoft-networking/tools/tree/main/src/uoft/switchconfig/cli",
)